### ISSUE TITLE
Anh Vỹ góp ý

### ISSUE THREAD

**Issue by tvhoang91** [tvhoang91/anuongbamien#20]
### Task
- [x] Nền màu xám
- [x] panel search chỉnh có border, màu, label to hơn
- [x] Trang liên hệ:  bỏ
- [x] footer: chủ shop a.Đin + sdt + dc: 404/5A Lê Hồng Phong, Nha Trang
- [x] breadcumb: bự hơn

**Comment by tvhoang91** [comment]
Done
